name: Publish Python 🐍 distribution to PyPI

on:
  push:
    branches:
      - master
    paths:
      - 'pyproject.toml'
      - 'topdesk_mcp/**'
      - '.github/workflows/pypi.yml'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv package manager
        run: pip install uv

      - name: Install build tools
        run: uv pip install build twine toml

      - name: Bump version in pyproject.toml
        id: bump_version
        run: |
          python -c "import toml; f='pyproject.toml'; d=toml.load(f); v=d['project']['version'].split('.'); v[-1]=str(int(v[-1])+1); d['project']['version']='.'.join(v); toml.dump(d, open(f, 'w'))"
          echo "::set-output name=new_version::$(python -c \"import toml; print(toml.load('pyproject.toml')['project']['version'])\")"

      - name: Build package
        run: uv pip run python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: uv pip run twine upload dist/*

      - name: Show new version
        run: echo "Published version ${{ steps.bump_version.outputs.new_version }} to PyPI"
