name: Run Pytest

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies with uv
        run: |
            pip install uv
            uv venv
            uv pip install -e .
            uv pip install -e ".[dev]" 

      - name: Run pytest
        run: uv run pytest
