name: Run Pytest

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv package manager
        run: pip install uv

      - name: Install dependencies with uv
        run: |
          uv pip install -r requirements.txt || uv pip install pytest
          
      - name: Run pytest
        run: uv pip run pytest
